// Code generated by rclgo-gen. DO NOT EDIT.

package unitree_go_msg
import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <unitree_go/msg/error.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("unitree_go/Error", ErrorTypeSupport)
	typemap.RegisterMessage("unitree_go/msg/Error", ErrorTypeSupport)
}

type Error struct {
	Source uint32 `yaml:"source"`
	State uint32 `yaml:"state"`
}

// NewError creates a new Error with default values.
func NewError() *Error {
	self := Error{}
	self.SetDefaults()
	return &self
}

func (t *Error) Clone() *Error {
	c := &Error{}
	c.Source = t.Source
	c.State = t.State
	return c
}

func (t *Error) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Error) SetDefaults() {
	t.Source = 0
	t.State = 0
}

func (t *Error) GetTypeSupport() types.MessageTypeSupport {
	return ErrorTypeSupport
}

// ErrorPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ErrorPublisher struct {
	*rclgo.Publisher
}

// NewErrorPublisher creates and returns a new publisher for the
// Error
func NewErrorPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ErrorPublisher, error) {
	pub, err := node.NewPublisher(topic_name, ErrorTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ErrorPublisher{pub}, nil
}

func (p *ErrorPublisher) Publish(msg *Error) error {
	return p.Publisher.Publish(msg)
}

// ErrorSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ErrorSubscription struct {
	*rclgo.Subscription
}

// ErrorSubscriptionCallback type is used to provide a subscription
// handler function for a ErrorSubscription.
type ErrorSubscriptionCallback func(msg *Error, info *rclgo.MessageInfo, err error)

// NewErrorSubscription creates and returns a new subscription for the
// Error
func NewErrorSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ErrorSubscriptionCallback) (*ErrorSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Error
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ErrorTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ErrorSubscription{sub}, nil
}

func (s *ErrorSubscription) TakeMessage(out *Error) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneErrorSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneErrorSlice(dst, src []Error) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ErrorTypeSupport types.MessageTypeSupport = _ErrorTypeSupport{}

type _ErrorTypeSupport struct{}

func (t _ErrorTypeSupport) New() types.Message {
	return NewError()
}

func (t _ErrorTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.unitree_go__msg__Error
	return (unsafe.Pointer)(C.unitree_go__msg__Error__create())
}

func (t _ErrorTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.unitree_go__msg__Error__destroy((*C.unitree_go__msg__Error)(pointer_to_free))
}

func (t _ErrorTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Error)
	mem := (*C.unitree_go__msg__Error)(dst)
	mem.source = C.uint32_t(m.Source)
	mem.state = C.uint32_t(m.State)
}

func (t _ErrorTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Error)
	mem := (*C.unitree_go__msg__Error)(ros2_message_buffer)
	m.Source = uint32(mem.source)
	m.State = uint32(mem.state)
}

func (t _ErrorTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__unitree_go__msg__Error())
}

type CError = C.unitree_go__msg__Error
type CError__Sequence = C.unitree_go__msg__Error__Sequence

func Error__Sequence_to_Go(goSlice *[]Error, cSlice CError__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Error, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ErrorTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Error__Sequence_to_C(cSlice *CError__Sequence, goSlice []Error) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.unitree_go__msg__Error)(C.malloc(C.sizeof_struct_unitree_go__msg__Error * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ErrorTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Error__Array_to_Go(goSlice []Error, cSlice []CError) {
	for i := 0; i < len(cSlice); i++ {
		ErrorTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Error__Array_to_C(cSlice []CError, goSlice []Error) {
	for i := 0; i < len(goSlice); i++ {
		ErrorTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
