// Code generated by rclgo-gen. DO NOT EDIT.

package unitree_go_msg
import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	primitives "github.com/merlindrones/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <unitree_go/msg/low_state.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("unitree_go/LowState", LowStateTypeSupport)
	typemap.RegisterMessage("unitree_go/msg/LowState", LowStateTypeSupport)
}

type LowState struct {
	Head [2]uint8 `yaml:"head"`
	LevelFlag uint8 `yaml:"level_flag"`
	FrameReserve uint8 `yaml:"frame_reserve"`
	Sn [2]uint32 `yaml:"sn"`
	Version [2]uint32 `yaml:"version"`
	Bandwidth uint16 `yaml:"bandwidth"`
	ImuState IMUState `yaml:"imu_state"`
	MotorState [20]MotorState `yaml:"motor_state"`
	BmsState BmsState `yaml:"bms_state"`
	FootForce [4]int16 `yaml:"foot_force"`
	FootForceEst [4]int16 `yaml:"foot_force_est"`
	Tick uint32 `yaml:"tick"`
	WirelessRemote [40]uint8 `yaml:"wireless_remote"`
	BitFlag uint8 `yaml:"bit_flag"`
	AdcReel float32 `yaml:"adc_reel"`
	TemperatureNtc1 int8 `yaml:"temperature_ntc1"`
	TemperatureNtc2 int8 `yaml:"temperature_ntc2"`
	PowerV float32 `yaml:"power_v"`
	PowerA float32 `yaml:"power_a"`
	FanFrequency [4]uint16 `yaml:"fan_frequency"`
	Reserve uint32 `yaml:"reserve"`
	Crc uint32 `yaml:"crc"`
}

// NewLowState creates a new LowState with default values.
func NewLowState() *LowState {
	self := LowState{}
	self.SetDefaults()
	return &self
}

func (t *LowState) Clone() *LowState {
	c := &LowState{}
	c.Head = t.Head
	c.LevelFlag = t.LevelFlag
	c.FrameReserve = t.FrameReserve
	c.Sn = t.Sn
	c.Version = t.Version
	c.Bandwidth = t.Bandwidth
	c.ImuState = *t.ImuState.Clone()
	CloneMotorStateSlice(c.MotorState[:], t.MotorState[:])
	c.BmsState = *t.BmsState.Clone()
	c.FootForce = t.FootForce
	c.FootForceEst = t.FootForceEst
	c.Tick = t.Tick
	c.WirelessRemote = t.WirelessRemote
	c.BitFlag = t.BitFlag
	c.AdcReel = t.AdcReel
	c.TemperatureNtc1 = t.TemperatureNtc1
	c.TemperatureNtc2 = t.TemperatureNtc2
	c.PowerV = t.PowerV
	c.PowerA = t.PowerA
	c.FanFrequency = t.FanFrequency
	c.Reserve = t.Reserve
	c.Crc = t.Crc
	return c
}

func (t *LowState) CloneMsg() types.Message {
	return t.Clone()
}

func (t *LowState) SetDefaults() {
	t.Head = [2]uint8{}
	t.LevelFlag = 0
	t.FrameReserve = 0
	t.Sn = [2]uint32{}
	t.Version = [2]uint32{}
	t.Bandwidth = 0
	t.ImuState.SetDefaults()
	for i := range t.MotorState {
		t.MotorState[i].SetDefaults()
	}
	t.BmsState.SetDefaults()
	t.FootForce = [4]int16{}
	t.FootForceEst = [4]int16{}
	t.Tick = 0
	t.WirelessRemote = [40]uint8{}
	t.BitFlag = 0
	t.AdcReel = 0
	t.TemperatureNtc1 = 0
	t.TemperatureNtc2 = 0
	t.PowerV = 0
	t.PowerA = 0
	t.FanFrequency = [4]uint16{}
	t.Reserve = 0
	t.Crc = 0
}

func (t *LowState) GetTypeSupport() types.MessageTypeSupport {
	return LowStateTypeSupport
}

// LowStatePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type LowStatePublisher struct {
	*rclgo.Publisher
}

// NewLowStatePublisher creates and returns a new publisher for the
// LowState
func NewLowStatePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*LowStatePublisher, error) {
	pub, err := node.NewPublisher(topic_name, LowStateTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &LowStatePublisher{pub}, nil
}

func (p *LowStatePublisher) Publish(msg *LowState) error {
	return p.Publisher.Publish(msg)
}

// LowStateSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type LowStateSubscription struct {
	*rclgo.Subscription
}

// LowStateSubscriptionCallback type is used to provide a subscription
// handler function for a LowStateSubscription.
type LowStateSubscriptionCallback func(msg *LowState, info *rclgo.MessageInfo, err error)

// NewLowStateSubscription creates and returns a new subscription for the
// LowState
func NewLowStateSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback LowStateSubscriptionCallback) (*LowStateSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg LowState
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, LowStateTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &LowStateSubscription{sub}, nil
}

func (s *LowStateSubscription) TakeMessage(out *LowState) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneLowStateSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneLowStateSlice(dst, src []LowState) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var LowStateTypeSupport types.MessageTypeSupport = _LowStateTypeSupport{}

type _LowStateTypeSupport struct{}

func (t _LowStateTypeSupport) New() types.Message {
	return NewLowState()
}

func (t _LowStateTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.unitree_go__msg__LowState
	return (unsafe.Pointer)(C.unitree_go__msg__LowState__create())
}

func (t _LowStateTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.unitree_go__msg__LowState__destroy((*C.unitree_go__msg__LowState)(pointer_to_free))
}

func (t _LowStateTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*LowState)
	mem := (*C.unitree_go__msg__LowState)(dst)
	cSlice_head := mem.head[:]
	primitives.Uint8__Array_to_C(*(*[]primitives.CUint8)(unsafe.Pointer(&cSlice_head)), m.Head[:])
	mem.level_flag = C.uint8_t(m.LevelFlag)
	mem.frame_reserve = C.uint8_t(m.FrameReserve)
	cSlice_sn := mem.sn[:]
	primitives.Uint32__Array_to_C(*(*[]primitives.CUint32)(unsafe.Pointer(&cSlice_sn)), m.Sn[:])
	cSlice_version := mem.version[:]
	primitives.Uint32__Array_to_C(*(*[]primitives.CUint32)(unsafe.Pointer(&cSlice_version)), m.Version[:])
	mem.bandwidth = C.uint16_t(m.Bandwidth)
	IMUStateTypeSupport.AsCStruct(unsafe.Pointer(&mem.imu_state), &m.ImuState)
	MotorState__Array_to_C(mem.motor_state[:], m.MotorState[:])
	BmsStateTypeSupport.AsCStruct(unsafe.Pointer(&mem.bms_state), &m.BmsState)
	cSlice_foot_force := mem.foot_force[:]
	primitives.Int16__Array_to_C(*(*[]primitives.CInt16)(unsafe.Pointer(&cSlice_foot_force)), m.FootForce[:])
	cSlice_foot_force_est := mem.foot_force_est[:]
	primitives.Int16__Array_to_C(*(*[]primitives.CInt16)(unsafe.Pointer(&cSlice_foot_force_est)), m.FootForceEst[:])
	mem.tick = C.uint32_t(m.Tick)
	cSlice_wireless_remote := mem.wireless_remote[:]
	primitives.Uint8__Array_to_C(*(*[]primitives.CUint8)(unsafe.Pointer(&cSlice_wireless_remote)), m.WirelessRemote[:])
	mem.bit_flag = C.uint8_t(m.BitFlag)
	mem.adc_reel = C.float(m.AdcReel)
	mem.temperature_ntc1 = C.int8_t(m.TemperatureNtc1)
	mem.temperature_ntc2 = C.int8_t(m.TemperatureNtc2)
	mem.power_v = C.float(m.PowerV)
	mem.power_a = C.float(m.PowerA)
	cSlice_fan_frequency := mem.fan_frequency[:]
	primitives.Uint16__Array_to_C(*(*[]primitives.CUint16)(unsafe.Pointer(&cSlice_fan_frequency)), m.FanFrequency[:])
	mem.reserve = C.uint32_t(m.Reserve)
	mem.crc = C.uint32_t(m.Crc)
}

func (t _LowStateTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*LowState)
	mem := (*C.unitree_go__msg__LowState)(ros2_message_buffer)
	cSlice_head := mem.head[:]
	primitives.Uint8__Array_to_Go(m.Head[:], *(*[]primitives.CUint8)(unsafe.Pointer(&cSlice_head)))
	m.LevelFlag = uint8(mem.level_flag)
	m.FrameReserve = uint8(mem.frame_reserve)
	cSlice_sn := mem.sn[:]
	primitives.Uint32__Array_to_Go(m.Sn[:], *(*[]primitives.CUint32)(unsafe.Pointer(&cSlice_sn)))
	cSlice_version := mem.version[:]
	primitives.Uint32__Array_to_Go(m.Version[:], *(*[]primitives.CUint32)(unsafe.Pointer(&cSlice_version)))
	m.Bandwidth = uint16(mem.bandwidth)
	IMUStateTypeSupport.AsGoStruct(&m.ImuState, unsafe.Pointer(&mem.imu_state))
	MotorState__Array_to_Go(m.MotorState[:], mem.motor_state[:])
	BmsStateTypeSupport.AsGoStruct(&m.BmsState, unsafe.Pointer(&mem.bms_state))
	cSlice_foot_force := mem.foot_force[:]
	primitives.Int16__Array_to_Go(m.FootForce[:], *(*[]primitives.CInt16)(unsafe.Pointer(&cSlice_foot_force)))
	cSlice_foot_force_est := mem.foot_force_est[:]
	primitives.Int16__Array_to_Go(m.FootForceEst[:], *(*[]primitives.CInt16)(unsafe.Pointer(&cSlice_foot_force_est)))
	m.Tick = uint32(mem.tick)
	cSlice_wireless_remote := mem.wireless_remote[:]
	primitives.Uint8__Array_to_Go(m.WirelessRemote[:], *(*[]primitives.CUint8)(unsafe.Pointer(&cSlice_wireless_remote)))
	m.BitFlag = uint8(mem.bit_flag)
	m.AdcReel = float32(mem.adc_reel)
	m.TemperatureNtc1 = int8(mem.temperature_ntc1)
	m.TemperatureNtc2 = int8(mem.temperature_ntc2)
	m.PowerV = float32(mem.power_v)
	m.PowerA = float32(mem.power_a)
	cSlice_fan_frequency := mem.fan_frequency[:]
	primitives.Uint16__Array_to_Go(m.FanFrequency[:], *(*[]primitives.CUint16)(unsafe.Pointer(&cSlice_fan_frequency)))
	m.Reserve = uint32(mem.reserve)
	m.Crc = uint32(mem.crc)
}

func (t _LowStateTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__unitree_go__msg__LowState())
}

type CLowState = C.unitree_go__msg__LowState
type CLowState__Sequence = C.unitree_go__msg__LowState__Sequence

func LowState__Sequence_to_Go(goSlice *[]LowState, cSlice CLowState__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]LowState, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		LowStateTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func LowState__Sequence_to_C(cSlice *CLowState__Sequence, goSlice []LowState) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.unitree_go__msg__LowState)(C.malloc(C.sizeof_struct_unitree_go__msg__LowState * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		LowStateTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func LowState__Array_to_Go(goSlice []LowState, cSlice []CLowState) {
	for i := 0; i < len(cSlice); i++ {
		LowStateTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func LowState__Array_to_C(cSlice []CLowState, goSlice []LowState) {
	for i := 0; i < len(goSlice); i++ {
		LowStateTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
