// Code generated by rclgo-gen. DO NOT EDIT.

package unitree_go_msg
import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	primitives "github.com/merlindrones/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <unitree_go/msg/motor_cmd.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("unitree_go/MotorCmd", MotorCmdTypeSupport)
	typemap.RegisterMessage("unitree_go/msg/MotorCmd", MotorCmdTypeSupport)
}

type MotorCmd struct {
	Mode uint8 `yaml:"mode"`
	Q float32 `yaml:"q"`
	Dq float32 `yaml:"dq"`
	Tau float32 `yaml:"tau"`
	Kp float32 `yaml:"kp"`
	Kd float32 `yaml:"kd"`
	Reserve [3]uint32 `yaml:"reserve"`
}

// NewMotorCmd creates a new MotorCmd with default values.
func NewMotorCmd() *MotorCmd {
	self := MotorCmd{}
	self.SetDefaults()
	return &self
}

func (t *MotorCmd) Clone() *MotorCmd {
	c := &MotorCmd{}
	c.Mode = t.Mode
	c.Q = t.Q
	c.Dq = t.Dq
	c.Tau = t.Tau
	c.Kp = t.Kp
	c.Kd = t.Kd
	c.Reserve = t.Reserve
	return c
}

func (t *MotorCmd) CloneMsg() types.Message {
	return t.Clone()
}

func (t *MotorCmd) SetDefaults() {
	t.Mode = 0
	t.Q = 0
	t.Dq = 0
	t.Tau = 0
	t.Kp = 0
	t.Kd = 0
	t.Reserve = [3]uint32{}
}

func (t *MotorCmd) GetTypeSupport() types.MessageTypeSupport {
	return MotorCmdTypeSupport
}

// MotorCmdPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type MotorCmdPublisher struct {
	*rclgo.Publisher
}

// NewMotorCmdPublisher creates and returns a new publisher for the
// MotorCmd
func NewMotorCmdPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*MotorCmdPublisher, error) {
	pub, err := node.NewPublisher(topic_name, MotorCmdTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &MotorCmdPublisher{pub}, nil
}

func (p *MotorCmdPublisher) Publish(msg *MotorCmd) error {
	return p.Publisher.Publish(msg)
}

// MotorCmdSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type MotorCmdSubscription struct {
	*rclgo.Subscription
}

// MotorCmdSubscriptionCallback type is used to provide a subscription
// handler function for a MotorCmdSubscription.
type MotorCmdSubscriptionCallback func(msg *MotorCmd, info *rclgo.MessageInfo, err error)

// NewMotorCmdSubscription creates and returns a new subscription for the
// MotorCmd
func NewMotorCmdSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback MotorCmdSubscriptionCallback) (*MotorCmdSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg MotorCmd
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, MotorCmdTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &MotorCmdSubscription{sub}, nil
}

func (s *MotorCmdSubscription) TakeMessage(out *MotorCmd) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneMotorCmdSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneMotorCmdSlice(dst, src []MotorCmd) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var MotorCmdTypeSupport types.MessageTypeSupport = _MotorCmdTypeSupport{}

type _MotorCmdTypeSupport struct{}

func (t _MotorCmdTypeSupport) New() types.Message {
	return NewMotorCmd()
}

func (t _MotorCmdTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.unitree_go__msg__MotorCmd
	return (unsafe.Pointer)(C.unitree_go__msg__MotorCmd__create())
}

func (t _MotorCmdTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.unitree_go__msg__MotorCmd__destroy((*C.unitree_go__msg__MotorCmd)(pointer_to_free))
}

func (t _MotorCmdTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*MotorCmd)
	mem := (*C.unitree_go__msg__MotorCmd)(dst)
	mem.mode = C.uint8_t(m.Mode)
	mem.q = C.float(m.Q)
	mem.dq = C.float(m.Dq)
	mem.tau = C.float(m.Tau)
	mem.kp = C.float(m.Kp)
	mem.kd = C.float(m.Kd)
	cSlice_reserve := mem.reserve[:]
	primitives.Uint32__Array_to_C(*(*[]primitives.CUint32)(unsafe.Pointer(&cSlice_reserve)), m.Reserve[:])
}

func (t _MotorCmdTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*MotorCmd)
	mem := (*C.unitree_go__msg__MotorCmd)(ros2_message_buffer)
	m.Mode = uint8(mem.mode)
	m.Q = float32(mem.q)
	m.Dq = float32(mem.dq)
	m.Tau = float32(mem.tau)
	m.Kp = float32(mem.kp)
	m.Kd = float32(mem.kd)
	cSlice_reserve := mem.reserve[:]
	primitives.Uint32__Array_to_Go(m.Reserve[:], *(*[]primitives.CUint32)(unsafe.Pointer(&cSlice_reserve)))
}

func (t _MotorCmdTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__unitree_go__msg__MotorCmd())
}

type CMotorCmd = C.unitree_go__msg__MotorCmd
type CMotorCmd__Sequence = C.unitree_go__msg__MotorCmd__Sequence

func MotorCmd__Sequence_to_Go(goSlice *[]MotorCmd, cSlice CMotorCmd__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]MotorCmd, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		MotorCmdTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func MotorCmd__Sequence_to_C(cSlice *CMotorCmd__Sequence, goSlice []MotorCmd) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.unitree_go__msg__MotorCmd)(C.malloc(C.sizeof_struct_unitree_go__msg__MotorCmd * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		MotorCmdTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func MotorCmd__Array_to_Go(goSlice []MotorCmd, cSlice []CMotorCmd) {
	for i := 0; i < len(cSlice); i++ {
		MotorCmdTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func MotorCmd__Array_to_C(cSlice []CMotorCmd, goSlice []MotorCmd) {
	for i := 0; i < len(goSlice); i++ {
		MotorCmdTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
