// Code generated by rclgo-gen. DO NOT EDIT.

package unitree_go_msg
import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	primitives "github.com/merlindrones/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <unitree_go/msg/res.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("unitree_go/Res", ResTypeSupport)
	typemap.RegisterMessage("unitree_go/msg/Res", ResTypeSupport)
}

type Res struct {
	Uuid string `yaml:"uuid"`
	Data []uint8 `yaml:"data"`
	Body string `yaml:"body"`
}

// NewRes creates a new Res with default values.
func NewRes() *Res {
	self := Res{}
	self.SetDefaults()
	return &self
}

func (t *Res) Clone() *Res {
	c := &Res{}
	c.Uuid = t.Uuid
	if t.Data != nil {
		c.Data = make([]uint8, len(t.Data))
		copy(c.Data, t.Data)
	}
	c.Body = t.Body
	return c
}

func (t *Res) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Res) SetDefaults() {
	t.Uuid = ""
	t.Data = nil
	t.Body = ""
}

func (t *Res) GetTypeSupport() types.MessageTypeSupport {
	return ResTypeSupport
}

// ResPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ResPublisher struct {
	*rclgo.Publisher
}

// NewResPublisher creates and returns a new publisher for the
// Res
func NewResPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ResPublisher, error) {
	pub, err := node.NewPublisher(topic_name, ResTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ResPublisher{pub}, nil
}

func (p *ResPublisher) Publish(msg *Res) error {
	return p.Publisher.Publish(msg)
}

// ResSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ResSubscription struct {
	*rclgo.Subscription
}

// ResSubscriptionCallback type is used to provide a subscription
// handler function for a ResSubscription.
type ResSubscriptionCallback func(msg *Res, info *rclgo.MessageInfo, err error)

// NewResSubscription creates and returns a new subscription for the
// Res
func NewResSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ResSubscriptionCallback) (*ResSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Res
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ResTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ResSubscription{sub}, nil
}

func (s *ResSubscription) TakeMessage(out *Res) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneResSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneResSlice(dst, src []Res) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ResTypeSupport types.MessageTypeSupport = _ResTypeSupport{}

type _ResTypeSupport struct{}

func (t _ResTypeSupport) New() types.Message {
	return NewRes()
}

func (t _ResTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.unitree_go__msg__Res
	return (unsafe.Pointer)(C.unitree_go__msg__Res__create())
}

func (t _ResTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.unitree_go__msg__Res__destroy((*C.unitree_go__msg__Res)(pointer_to_free))
}

func (t _ResTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Res)
	mem := (*C.unitree_go__msg__Res)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.uuid), m.Uuid)
	primitives.Uint8__Sequence_to_C((*primitives.CUint8__Sequence)(unsafe.Pointer(&mem.data)), m.Data)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.body), m.Body)
}

func (t _ResTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Res)
	mem := (*C.unitree_go__msg__Res)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.Uuid, unsafe.Pointer(&mem.uuid))
	primitives.Uint8__Sequence_to_Go(&m.Data, *(*primitives.CUint8__Sequence)(unsafe.Pointer(&mem.data)))
	primitives.StringAsGoStruct(&m.Body, unsafe.Pointer(&mem.body))
}

func (t _ResTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__unitree_go__msg__Res())
}

type CRes = C.unitree_go__msg__Res
type CRes__Sequence = C.unitree_go__msg__Res__Sequence

func Res__Sequence_to_Go(goSlice *[]Res, cSlice CRes__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Res, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ResTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Res__Sequence_to_C(cSlice *CRes__Sequence, goSlice []Res) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.unitree_go__msg__Res)(C.malloc(C.sizeof_struct_unitree_go__msg__Res * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ResTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Res__Array_to_Go(goSlice []Res, cSlice []CRes) {
	for i := 0; i < len(cSlice); i++ {
		ResTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Res__Array_to_C(cSlice []CRes, goSlice []Res) {
	for i := 0; i < len(goSlice); i++ {
		ResTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
