// Code generated by rclgo-gen. DO NOT EDIT.

package unitree_go_msg
import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	primitives "github.com/merlindrones/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <unitree_go/msg/sport_mode_cmd.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("unitree_go/SportModeCmd", SportModeCmdTypeSupport)
	typemap.RegisterMessage("unitree_go/msg/SportModeCmd", SportModeCmdTypeSupport)
}

type SportModeCmd struct {
	Mode uint8 `yaml:"mode"`
	GaitType uint8 `yaml:"gait_type"`
	SpeedLevel uint8 `yaml:"speed_level"`
	FootRaiseHeight float32 `yaml:"foot_raise_height"`
	BodyHeight float32 `yaml:"body_height"`
	Position [2]float32 `yaml:"position"`
	Euler [3]float32 `yaml:"euler"`
	Velocity [2]float32 `yaml:"velocity"`
	YawSpeed float32 `yaml:"yaw_speed"`
	BmsCmd BmsCmd `yaml:"bms_cmd"`
	PathPoint [30]PathPoint `yaml:"path_point"`
}

// NewSportModeCmd creates a new SportModeCmd with default values.
func NewSportModeCmd() *SportModeCmd {
	self := SportModeCmd{}
	self.SetDefaults()
	return &self
}

func (t *SportModeCmd) Clone() *SportModeCmd {
	c := &SportModeCmd{}
	c.Mode = t.Mode
	c.GaitType = t.GaitType
	c.SpeedLevel = t.SpeedLevel
	c.FootRaiseHeight = t.FootRaiseHeight
	c.BodyHeight = t.BodyHeight
	c.Position = t.Position
	c.Euler = t.Euler
	c.Velocity = t.Velocity
	c.YawSpeed = t.YawSpeed
	c.BmsCmd = *t.BmsCmd.Clone()
	ClonePathPointSlice(c.PathPoint[:], t.PathPoint[:])
	return c
}

func (t *SportModeCmd) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SportModeCmd) SetDefaults() {
	t.Mode = 0
	t.GaitType = 0
	t.SpeedLevel = 0
	t.FootRaiseHeight = 0
	t.BodyHeight = 0
	t.Position = [2]float32{}
	t.Euler = [3]float32{}
	t.Velocity = [2]float32{}
	t.YawSpeed = 0
	t.BmsCmd.SetDefaults()
	for i := range t.PathPoint {
		t.PathPoint[i].SetDefaults()
	}
}

func (t *SportModeCmd) GetTypeSupport() types.MessageTypeSupport {
	return SportModeCmdTypeSupport
}

// SportModeCmdPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SportModeCmdPublisher struct {
	*rclgo.Publisher
}

// NewSportModeCmdPublisher creates and returns a new publisher for the
// SportModeCmd
func NewSportModeCmdPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SportModeCmdPublisher, error) {
	pub, err := node.NewPublisher(topic_name, SportModeCmdTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SportModeCmdPublisher{pub}, nil
}

func (p *SportModeCmdPublisher) Publish(msg *SportModeCmd) error {
	return p.Publisher.Publish(msg)
}

// SportModeCmdSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SportModeCmdSubscription struct {
	*rclgo.Subscription
}

// SportModeCmdSubscriptionCallback type is used to provide a subscription
// handler function for a SportModeCmdSubscription.
type SportModeCmdSubscriptionCallback func(msg *SportModeCmd, info *rclgo.MessageInfo, err error)

// NewSportModeCmdSubscription creates and returns a new subscription for the
// SportModeCmd
func NewSportModeCmdSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SportModeCmdSubscriptionCallback) (*SportModeCmdSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SportModeCmd
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SportModeCmdTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SportModeCmdSubscription{sub}, nil
}

func (s *SportModeCmdSubscription) TakeMessage(out *SportModeCmd) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSportModeCmdSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSportModeCmdSlice(dst, src []SportModeCmd) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SportModeCmdTypeSupport types.MessageTypeSupport = _SportModeCmdTypeSupport{}

type _SportModeCmdTypeSupport struct{}

func (t _SportModeCmdTypeSupport) New() types.Message {
	return NewSportModeCmd()
}

func (t _SportModeCmdTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.unitree_go__msg__SportModeCmd
	return (unsafe.Pointer)(C.unitree_go__msg__SportModeCmd__create())
}

func (t _SportModeCmdTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.unitree_go__msg__SportModeCmd__destroy((*C.unitree_go__msg__SportModeCmd)(pointer_to_free))
}

func (t _SportModeCmdTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SportModeCmd)
	mem := (*C.unitree_go__msg__SportModeCmd)(dst)
	mem.mode = C.uint8_t(m.Mode)
	mem.gait_type = C.uint8_t(m.GaitType)
	mem.speed_level = C.uint8_t(m.SpeedLevel)
	mem.foot_raise_height = C.float(m.FootRaiseHeight)
	mem.body_height = C.float(m.BodyHeight)
	cSlice_position := mem.position[:]
	primitives.Float32__Array_to_C(*(*[]primitives.CFloat32)(unsafe.Pointer(&cSlice_position)), m.Position[:])
	cSlice_euler := mem.euler[:]
	primitives.Float32__Array_to_C(*(*[]primitives.CFloat32)(unsafe.Pointer(&cSlice_euler)), m.Euler[:])
	cSlice_velocity := mem.velocity[:]
	primitives.Float32__Array_to_C(*(*[]primitives.CFloat32)(unsafe.Pointer(&cSlice_velocity)), m.Velocity[:])
	mem.yaw_speed = C.float(m.YawSpeed)
	BmsCmdTypeSupport.AsCStruct(unsafe.Pointer(&mem.bms_cmd), &m.BmsCmd)
	PathPoint__Array_to_C(mem.path_point[:], m.PathPoint[:])
}

func (t _SportModeCmdTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SportModeCmd)
	mem := (*C.unitree_go__msg__SportModeCmd)(ros2_message_buffer)
	m.Mode = uint8(mem.mode)
	m.GaitType = uint8(mem.gait_type)
	m.SpeedLevel = uint8(mem.speed_level)
	m.FootRaiseHeight = float32(mem.foot_raise_height)
	m.BodyHeight = float32(mem.body_height)
	cSlice_position := mem.position[:]
	primitives.Float32__Array_to_Go(m.Position[:], *(*[]primitives.CFloat32)(unsafe.Pointer(&cSlice_position)))
	cSlice_euler := mem.euler[:]
	primitives.Float32__Array_to_Go(m.Euler[:], *(*[]primitives.CFloat32)(unsafe.Pointer(&cSlice_euler)))
	cSlice_velocity := mem.velocity[:]
	primitives.Float32__Array_to_Go(m.Velocity[:], *(*[]primitives.CFloat32)(unsafe.Pointer(&cSlice_velocity)))
	m.YawSpeed = float32(mem.yaw_speed)
	BmsCmdTypeSupport.AsGoStruct(&m.BmsCmd, unsafe.Pointer(&mem.bms_cmd))
	PathPoint__Array_to_Go(m.PathPoint[:], mem.path_point[:])
}

func (t _SportModeCmdTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__unitree_go__msg__SportModeCmd())
}

type CSportModeCmd = C.unitree_go__msg__SportModeCmd
type CSportModeCmd__Sequence = C.unitree_go__msg__SportModeCmd__Sequence

func SportModeCmd__Sequence_to_Go(goSlice *[]SportModeCmd, cSlice CSportModeCmd__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SportModeCmd, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SportModeCmdTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SportModeCmd__Sequence_to_C(cSlice *CSportModeCmd__Sequence, goSlice []SportModeCmd) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.unitree_go__msg__SportModeCmd)(C.malloc(C.sizeof_struct_unitree_go__msg__SportModeCmd * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SportModeCmdTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SportModeCmd__Array_to_Go(goSlice []SportModeCmd, cSlice []CSportModeCmd) {
	for i := 0; i < len(cSlice); i++ {
		SportModeCmdTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SportModeCmd__Array_to_C(cSlice []CSportModeCmd, goSlice []SportModeCmd) {
	for i := 0; i < len(goSlice); i++ {
		SportModeCmdTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
