// Code generated by rclgo-gen. DO NOT EDIT.

package unitree_go_msg
import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <unitree_go/msg/uwb_switch.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("unitree_go/UwbSwitch", UwbSwitchTypeSupport)
	typemap.RegisterMessage("unitree_go/msg/UwbSwitch", UwbSwitchTypeSupport)
}

type UwbSwitch struct {
	Enabled uint8 `yaml:"enabled"`
}

// NewUwbSwitch creates a new UwbSwitch with default values.
func NewUwbSwitch() *UwbSwitch {
	self := UwbSwitch{}
	self.SetDefaults()
	return &self
}

func (t *UwbSwitch) Clone() *UwbSwitch {
	c := &UwbSwitch{}
	c.Enabled = t.Enabled
	return c
}

func (t *UwbSwitch) CloneMsg() types.Message {
	return t.Clone()
}

func (t *UwbSwitch) SetDefaults() {
	t.Enabled = 0
}

func (t *UwbSwitch) GetTypeSupport() types.MessageTypeSupport {
	return UwbSwitchTypeSupport
}

// UwbSwitchPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type UwbSwitchPublisher struct {
	*rclgo.Publisher
}

// NewUwbSwitchPublisher creates and returns a new publisher for the
// UwbSwitch
func NewUwbSwitchPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*UwbSwitchPublisher, error) {
	pub, err := node.NewPublisher(topic_name, UwbSwitchTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &UwbSwitchPublisher{pub}, nil
}

func (p *UwbSwitchPublisher) Publish(msg *UwbSwitch) error {
	return p.Publisher.Publish(msg)
}

// UwbSwitchSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type UwbSwitchSubscription struct {
	*rclgo.Subscription
}

// UwbSwitchSubscriptionCallback type is used to provide a subscription
// handler function for a UwbSwitchSubscription.
type UwbSwitchSubscriptionCallback func(msg *UwbSwitch, info *rclgo.MessageInfo, err error)

// NewUwbSwitchSubscription creates and returns a new subscription for the
// UwbSwitch
func NewUwbSwitchSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback UwbSwitchSubscriptionCallback) (*UwbSwitchSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg UwbSwitch
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, UwbSwitchTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &UwbSwitchSubscription{sub}, nil
}

func (s *UwbSwitchSubscription) TakeMessage(out *UwbSwitch) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneUwbSwitchSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneUwbSwitchSlice(dst, src []UwbSwitch) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var UwbSwitchTypeSupport types.MessageTypeSupport = _UwbSwitchTypeSupport{}

type _UwbSwitchTypeSupport struct{}

func (t _UwbSwitchTypeSupport) New() types.Message {
	return NewUwbSwitch()
}

func (t _UwbSwitchTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.unitree_go__msg__UwbSwitch
	return (unsafe.Pointer)(C.unitree_go__msg__UwbSwitch__create())
}

func (t _UwbSwitchTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.unitree_go__msg__UwbSwitch__destroy((*C.unitree_go__msg__UwbSwitch)(pointer_to_free))
}

func (t _UwbSwitchTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*UwbSwitch)
	mem := (*C.unitree_go__msg__UwbSwitch)(dst)
	mem.enabled = C.uint8_t(m.Enabled)
}

func (t _UwbSwitchTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*UwbSwitch)
	mem := (*C.unitree_go__msg__UwbSwitch)(ros2_message_buffer)
	m.Enabled = uint8(mem.enabled)
}

func (t _UwbSwitchTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__unitree_go__msg__UwbSwitch())
}

type CUwbSwitch = C.unitree_go__msg__UwbSwitch
type CUwbSwitch__Sequence = C.unitree_go__msg__UwbSwitch__Sequence

func UwbSwitch__Sequence_to_Go(goSlice *[]UwbSwitch, cSlice CUwbSwitch__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]UwbSwitch, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		UwbSwitchTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func UwbSwitch__Sequence_to_C(cSlice *CUwbSwitch__Sequence, goSlice []UwbSwitch) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.unitree_go__msg__UwbSwitch)(C.malloc(C.sizeof_struct_unitree_go__msg__UwbSwitch * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		UwbSwitchTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func UwbSwitch__Array_to_Go(goSlice []UwbSwitch, cSlice []CUwbSwitch) {
	for i := 0; i < len(cSlice); i++ {
		UwbSwitchTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func UwbSwitch__Array_to_C(cSlice []CUwbSwitch, goSlice []UwbSwitch) {
	for i := 0; i < len(goSlice); i++ {
		UwbSwitchTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
