server:
  http:
    host: "0.0.0.0"
    port: 8080
    request_max_size: 1048576
log:
  level:
    - logger: fsttm_server
      level: DEBUG
vad:
    vad_aggressiveness: 3
    device: 0
    rate: 16000
stt:
    model: "small.en"
tts:
    model: "tts_models/en/ljspeech/tacotron2-DDC"
