server:
  http:
    host: "0.0.0.0"
    port: 8080
    request_max_size: 1048576
log:
  level:
    - logger: gpt_fsttm_server
      level: INFO
    - logger: gpt_fsttm_server.ears
      level: INFO
    - logger: gpt_fsttm_server.whisper
      level: DEBUG
vad:
    vad_aggressiveness: 3
    device: 0
    rate: 16000
stt:
    model: "small.en"
tts:
    model: "tts_models/en/ljspeech/tacotron2-DDC"
gpt:
    n_ctx: 2048
    temp: 0.7
    top_k: 40
    top_p: 0.5
    repeat_last_n: 256
    n_batch: 1024
    repeat_penalty: 1.17647
    model: "./models/7B/ggml-vicuna-7b-1.1-q5_1.bin"
    n_threads: 8
    n_predict: 2048
    safeword: "coyotes"
    conversation: "vicuna_v1.1"