// Code generated by rclgo-gen. DO NOT EDIT.

package unitree_api_msg
import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <unitree_api/msg/request_identity.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("unitree_api/RequestIdentity", RequestIdentityTypeSupport)
	typemap.RegisterMessage("unitree_api/msg/RequestIdentity", RequestIdentityTypeSupport)
}

type RequestIdentity struct {
	Id int64 `yaml:"id"`
	ApiId int64 `yaml:"api_id"`
}

// NewRequestIdentity creates a new RequestIdentity with default values.
func NewRequestIdentity() *RequestIdentity {
	self := RequestIdentity{}
	self.SetDefaults()
	return &self
}

func (t *RequestIdentity) Clone() *RequestIdentity {
	c := &RequestIdentity{}
	c.Id = t.Id
	c.ApiId = t.ApiId
	return c
}

func (t *RequestIdentity) CloneMsg() types.Message {
	return t.Clone()
}

func (t *RequestIdentity) SetDefaults() {
	t.Id = 0
	t.ApiId = 0
}

func (t *RequestIdentity) GetTypeSupport() types.MessageTypeSupport {
	return RequestIdentityTypeSupport
}

// RequestIdentityPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type RequestIdentityPublisher struct {
	*rclgo.Publisher
}

// NewRequestIdentityPublisher creates and returns a new publisher for the
// RequestIdentity
func NewRequestIdentityPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*RequestIdentityPublisher, error) {
	pub, err := node.NewPublisher(topic_name, RequestIdentityTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &RequestIdentityPublisher{pub}, nil
}

func (p *RequestIdentityPublisher) Publish(msg *RequestIdentity) error {
	return p.Publisher.Publish(msg)
}

// RequestIdentitySubscription wraps rclgo.Subscription to provide type safe helper
// functions
type RequestIdentitySubscription struct {
	*rclgo.Subscription
}

// RequestIdentitySubscriptionCallback type is used to provide a subscription
// handler function for a RequestIdentitySubscription.
type RequestIdentitySubscriptionCallback func(msg *RequestIdentity, info *rclgo.MessageInfo, err error)

// NewRequestIdentitySubscription creates and returns a new subscription for the
// RequestIdentity
func NewRequestIdentitySubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback RequestIdentitySubscriptionCallback) (*RequestIdentitySubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg RequestIdentity
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, RequestIdentityTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &RequestIdentitySubscription{sub}, nil
}

func (s *RequestIdentitySubscription) TakeMessage(out *RequestIdentity) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneRequestIdentitySlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneRequestIdentitySlice(dst, src []RequestIdentity) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var RequestIdentityTypeSupport types.MessageTypeSupport = _RequestIdentityTypeSupport{}

type _RequestIdentityTypeSupport struct{}

func (t _RequestIdentityTypeSupport) New() types.Message {
	return NewRequestIdentity()
}

func (t _RequestIdentityTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.unitree_api__msg__RequestIdentity
	return (unsafe.Pointer)(C.unitree_api__msg__RequestIdentity__create())
}

func (t _RequestIdentityTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.unitree_api__msg__RequestIdentity__destroy((*C.unitree_api__msg__RequestIdentity)(pointer_to_free))
}

func (t _RequestIdentityTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*RequestIdentity)
	mem := (*C.unitree_api__msg__RequestIdentity)(dst)
	mem.id = C.int64_t(m.Id)
	mem.api_id = C.int64_t(m.ApiId)
}

func (t _RequestIdentityTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*RequestIdentity)
	mem := (*C.unitree_api__msg__RequestIdentity)(ros2_message_buffer)
	m.Id = int64(mem.id)
	m.ApiId = int64(mem.api_id)
}

func (t _RequestIdentityTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__unitree_api__msg__RequestIdentity())
}

type CRequestIdentity = C.unitree_api__msg__RequestIdentity
type CRequestIdentity__Sequence = C.unitree_api__msg__RequestIdentity__Sequence

func RequestIdentity__Sequence_to_Go(goSlice *[]RequestIdentity, cSlice CRequestIdentity__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]RequestIdentity, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		RequestIdentityTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func RequestIdentity__Sequence_to_C(cSlice *CRequestIdentity__Sequence, goSlice []RequestIdentity) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.unitree_api__msg__RequestIdentity)(C.malloc(C.sizeof_struct_unitree_api__msg__RequestIdentity * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		RequestIdentityTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func RequestIdentity__Array_to_Go(goSlice []RequestIdentity, cSlice []CRequestIdentity) {
	for i := 0; i < len(cSlice); i++ {
		RequestIdentityTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func RequestIdentity__Array_to_C(cSlice []CRequestIdentity, goSlice []RequestIdentity) {
	for i := 0; i < len(goSlice); i++ {
		RequestIdentityTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
