// Code generated by rclgo-gen. DO NOT EDIT.

package unitree_api_msg
import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	primitives "github.com/merlindrones/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <unitree_api/msg/response.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("unitree_api/Response", ResponseTypeSupport)
	typemap.RegisterMessage("unitree_api/msg/Response", ResponseTypeSupport)
}

type Response struct {
	Header ResponseHeader `yaml:"header"`
	Data string `yaml:"data"`
	Binary []int8 `yaml:"binary"`
}

// NewResponse creates a new Response with default values.
func NewResponse() *Response {
	self := Response{}
	self.SetDefaults()
	return &self
}

func (t *Response) Clone() *Response {
	c := &Response{}
	c.Header = *t.Header.Clone()
	c.Data = t.Data
	if t.Binary != nil {
		c.Binary = make([]int8, len(t.Binary))
		copy(c.Binary, t.Binary)
	}
	return c
}

func (t *Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Response) SetDefaults() {
	t.Header.SetDefaults()
	t.Data = ""
	t.Binary = nil
}

func (t *Response) GetTypeSupport() types.MessageTypeSupport {
	return ResponseTypeSupport
}

// ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ResponsePublisher struct {
	*rclgo.Publisher
}

// NewResponsePublisher creates and returns a new publisher for the
// Response
func NewResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ResponsePublisher{pub}, nil
}

func (p *ResponsePublisher) Publish(msg *Response) error {
	return p.Publisher.Publish(msg)
}

// ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ResponseSubscription struct {
	*rclgo.Subscription
}

// ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a ResponseSubscription.
type ResponseSubscriptionCallback func(msg *Response, info *rclgo.MessageInfo, err error)

// NewResponseSubscription creates and returns a new subscription for the
// Response
func NewResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ResponseSubscriptionCallback) (*ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ResponseSubscription{sub}, nil
}

func (s *ResponseSubscription) TakeMessage(out *Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneResponseSlice(dst, src []Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ResponseTypeSupport types.MessageTypeSupport = _ResponseTypeSupport{}

type _ResponseTypeSupport struct{}

func (t _ResponseTypeSupport) New() types.Message {
	return NewResponse()
}

func (t _ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.unitree_api__msg__Response
	return (unsafe.Pointer)(C.unitree_api__msg__Response__create())
}

func (t _ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.unitree_api__msg__Response__destroy((*C.unitree_api__msg__Response)(pointer_to_free))
}

func (t _ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Response)
	mem := (*C.unitree_api__msg__Response)(dst)
	ResponseHeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.data), m.Data)
	primitives.Int8__Sequence_to_C((*primitives.CInt8__Sequence)(unsafe.Pointer(&mem.binary)), m.Binary)
}

func (t _ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Response)
	mem := (*C.unitree_api__msg__Response)(ros2_message_buffer)
	ResponseHeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	primitives.StringAsGoStruct(&m.Data, unsafe.Pointer(&mem.data))
	primitives.Int8__Sequence_to_Go(&m.Binary, *(*primitives.CInt8__Sequence)(unsafe.Pointer(&mem.binary)))
}

func (t _ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__unitree_api__msg__Response())
}

type CResponse = C.unitree_api__msg__Response
type CResponse__Sequence = C.unitree_api__msg__Response__Sequence

func Response__Sequence_to_Go(goSlice *[]Response, cSlice CResponse__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Response__Sequence_to_C(cSlice *CResponse__Sequence, goSlice []Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.unitree_api__msg__Response)(C.malloc(C.sizeof_struct_unitree_api__msg__Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Response__Array_to_Go(goSlice []Response, cSlice []CResponse) {
	for i := 0; i < len(cSlice); i++ {
		ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Response__Array_to_C(cSlice []CResponse, goSlice []Response) {
	for i := 0; i < len(goSlice); i++ {
		ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
