// Code generated by rclgo-gen. DO NOT EDIT.

package unitree_api_msg
import (
	"unsafe"

	"github.com/merlindrones/rclgo/pkg/rclgo"
	"github.com/merlindrones/rclgo/pkg/rclgo/types"
	"github.com/merlindrones/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <unitree_api/msg/response_header.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("unitree_api/ResponseHeader", ResponseHeaderTypeSupport)
	typemap.RegisterMessage("unitree_api/msg/ResponseHeader", ResponseHeaderTypeSupport)
}

type ResponseHeader struct {
	Identity RequestIdentity `yaml:"identity"`
	Status ResponseStatus `yaml:"status"`
}

// NewResponseHeader creates a new ResponseHeader with default values.
func NewResponseHeader() *ResponseHeader {
	self := ResponseHeader{}
	self.SetDefaults()
	return &self
}

func (t *ResponseHeader) Clone() *ResponseHeader {
	c := &ResponseHeader{}
	c.Identity = *t.Identity.Clone()
	c.Status = *t.Status.Clone()
	return c
}

func (t *ResponseHeader) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ResponseHeader) SetDefaults() {
	t.Identity.SetDefaults()
	t.Status.SetDefaults()
}

func (t *ResponseHeader) GetTypeSupport() types.MessageTypeSupport {
	return ResponseHeaderTypeSupport
}

// ResponseHeaderPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ResponseHeaderPublisher struct {
	*rclgo.Publisher
}

// NewResponseHeaderPublisher creates and returns a new publisher for the
// ResponseHeader
func NewResponseHeaderPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ResponseHeaderPublisher, error) {
	pub, err := node.NewPublisher(topic_name, ResponseHeaderTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ResponseHeaderPublisher{pub}, nil
}

func (p *ResponseHeaderPublisher) Publish(msg *ResponseHeader) error {
	return p.Publisher.Publish(msg)
}

// ResponseHeaderSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ResponseHeaderSubscription struct {
	*rclgo.Subscription
}

// ResponseHeaderSubscriptionCallback type is used to provide a subscription
// handler function for a ResponseHeaderSubscription.
type ResponseHeaderSubscriptionCallback func(msg *ResponseHeader, info *rclgo.MessageInfo, err error)

// NewResponseHeaderSubscription creates and returns a new subscription for the
// ResponseHeader
func NewResponseHeaderSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ResponseHeaderSubscriptionCallback) (*ResponseHeaderSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ResponseHeader
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ResponseHeaderTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ResponseHeaderSubscription{sub}, nil
}

func (s *ResponseHeaderSubscription) TakeMessage(out *ResponseHeader) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneResponseHeaderSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneResponseHeaderSlice(dst, src []ResponseHeader) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ResponseHeaderTypeSupport types.MessageTypeSupport = _ResponseHeaderTypeSupport{}

type _ResponseHeaderTypeSupport struct{}

func (t _ResponseHeaderTypeSupport) New() types.Message {
	return NewResponseHeader()
}

func (t _ResponseHeaderTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.unitree_api__msg__ResponseHeader
	return (unsafe.Pointer)(C.unitree_api__msg__ResponseHeader__create())
}

func (t _ResponseHeaderTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.unitree_api__msg__ResponseHeader__destroy((*C.unitree_api__msg__ResponseHeader)(pointer_to_free))
}

func (t _ResponseHeaderTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ResponseHeader)
	mem := (*C.unitree_api__msg__ResponseHeader)(dst)
	RequestIdentityTypeSupport.AsCStruct(unsafe.Pointer(&mem.identity), &m.Identity)
	ResponseStatusTypeSupport.AsCStruct(unsafe.Pointer(&mem.status), &m.Status)
}

func (t _ResponseHeaderTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ResponseHeader)
	mem := (*C.unitree_api__msg__ResponseHeader)(ros2_message_buffer)
	RequestIdentityTypeSupport.AsGoStruct(&m.Identity, unsafe.Pointer(&mem.identity))
	ResponseStatusTypeSupport.AsGoStruct(&m.Status, unsafe.Pointer(&mem.status))
}

func (t _ResponseHeaderTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__unitree_api__msg__ResponseHeader())
}

type CResponseHeader = C.unitree_api__msg__ResponseHeader
type CResponseHeader__Sequence = C.unitree_api__msg__ResponseHeader__Sequence

func ResponseHeader__Sequence_to_Go(goSlice *[]ResponseHeader, cSlice CResponseHeader__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ResponseHeader, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ResponseHeaderTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ResponseHeader__Sequence_to_C(cSlice *CResponseHeader__Sequence, goSlice []ResponseHeader) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.unitree_api__msg__ResponseHeader)(C.malloc(C.sizeof_struct_unitree_api__msg__ResponseHeader * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ResponseHeaderTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ResponseHeader__Array_to_Go(goSlice []ResponseHeader, cSlice []CResponseHeader) {
	for i := 0; i < len(cSlice); i++ {
		ResponseHeaderTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ResponseHeader__Array_to_C(cSlice []CResponseHeader, goSlice []ResponseHeader) {
	for i := 0; i < len(goSlice); i++ {
		ResponseHeaderTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
