// Code generated by rclgo-gen. DO NOT EDIT.

package msgs

import (
	_ "github.com/ibnHatab/fsttm/go/internal/rosmsgs/unitree_api/msg" //
	_ "github.com/ibnHatab/fsttm/go/internal/rosmsgs/unitree_go/msg" //
)
